### ISSUE TITLE
Support replacing storage_account when changing account type

### ISSUE THREAD

**Issue by discordianfish** [terraform-providers/terraform-provider-azure#27]
### Terraform Version
- 0.9.8

### Affected Resource(s)
- azurerm_storage_account

### Expected Behavior
Since the account type can't be updated, I expected terraform to replace the resource instead.

### Actual Behavior
What actually happened?
```
* module.workers.azurerm_storage_account.tectonic_worker: 1 error(s) occurred:

* azurerm_storage_account.tectonic_worker: Error updating Azure Storage Account type "c99c88ef": storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="StorageAccountTypeConversionNotAllowed" Message="Storage account type cannot be changed to Premium_LRS."
```

### Steps to Reproduce
1. Create a Standard_LRS storage account with terraform and `terraform apply`
2. Change the tier to Premium_LRS storage account and `terraform apply`

**Comment by tombuildsstuff** [comment]
Hey @discordianfish 

This is a bug affecting the [AzureRM Provider](https://github.com/terraform-providers/terraform-provider-azurerm) repository - this repository is instead for the older Service Management (`Azure` / old portal). As such - I'm going to migrate this issue across to the new repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/110

Sorry for the inconvenience 

Thanks!

**Comment by discordianfish** [comment]
Do'h, sorry and thanks for moving!
