### ISSUE TITLE
Public IP address not shown in output until after 'terraform refresh'

### ISSUE THREAD

**Issue by andretost** [terraform-providers/terraform-provider-azure#28]
### Terraform Version
0.9.11

### Affected Resource(s)
azurerm_public_ip

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```resource "azurerm_public_ip" "andretestip" {
    name = "andretestip"
    location = "West US"
    resource_group_name = "${azurerm_resource_group.andretest.name}"
    public_ip_address_allocation = "dynamic"

    tags {
        environment = "AndreDemo"
    }
}

output "VM Public IP" {
  value = "${azurerm_public_ip.andretestip.ip_address}"
}
```

### Debug Output
No warnings in the debug output.

### Panic Output
No.

### Expected Behavior
I would have expected to see the defined output at the end of running 'terraform apply'.

### Actual Behavior
The apply completed successfully, there are no warnings or errors and my resources are deployed exactly as expected. However, the output does not show up at all. Only after I run 'terraform refresh', the output is now displayed. I assume the public IP address is allocated during resource creation and thus would assume that the ip_address attribute is know. I see that it is not listed in the state file after the original apply, and only gets added after running refresh.
This may actually be working as designed, but I don't quite understand why the IP address is not available or shown, or what kind of workaround I could use to make it appear.

**Comment by tombuildsstuff** [comment]
Hey @andretost 

Thanks for opening this issue :)

This repository is for the older [Azure Service Management Provider](http://terraform.io/docs/providers/azure/index.html), whereas the resources you're referring too are for the [Azure Resource Manager Provider](http://terraform.io/docs/providers/azurerm/index.html). As such I've [moved this issue over to the AzureRM Provider repository](https://github.com/terraform-providers/terraform-provider-azurerm/issues/159) - where we'll take a look into this :)

Thanks!
